logging:
  level:
    io:
      pivotal: info

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote

security:
  basic:
    enabled: false

management:
  security:
    enabled: false


